### ISSUE TITLE
[Bug/Model Request]: 

### ISSUE THREAD

**Issue by john-pome** [qdrant/fastembed#354]
### What happened?

Unable to install bundled Qdrant client and fastembed via pip in a virtualenv. Python 3.11, Linux ARM 64

```
virtualenv -p python3.11 .env
source .env/bin/activate
pip install qdrant-client[fastembed]
```

Lots of normal output, then a failure building Pystemmer

```
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Ilibstemmer_c-2.2.0/include -I/home/johnsigmon/programming/.env/include -I/usr/include/python3.11 -c src/Stemmer.c -o build/temp.linux-aarch64-cpython-311/src/Stemmer.o
      src/Stemmer.c:6:10: fatal error: Python.h: No such file or directory
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyStemmer
  Running setup.py clean for PyStemmer
Failed to build PyStemmer
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (PyStemmer)
```

Same result for `python -m venv venv` instead of `virtualenv`.

Interestingly, just to try it, I retested with python 3.10 and these examples do work with 3.10. However I would have to downgrade my python environment in my production application or risk it being unreliable in production on 3.11 (since I'm running 3.11 in production). 

Is this a known issue or am I missing something?

### What Python version are you on? e.g. python --version

3.10.12 and 3.11.10

### Version

0.2.7 (Latest)

### What os are you seeing the problem on?

Linux

**Comment by joein** [comment]
Hi @john-pome 

Could you please try out fastembed 0.4.1?
We replaced pystemmer with py-rust-stemmers

**Comment by john-pome** [comment]
Hey thanks for the response. Unfortunately I ran into several other issues after this (I ended up just downgrading to 3.10). Most notably being that 4/10 times my service attempted a connection to my Qdrant Cloud there was a connection failure on Qdrant's end. I ended up refactoring to use a different vector database entirely. Sorry I can't help test this out, feel free to close.

**Comment by Dylancouzon** [comment]
`PyStemmer` was replaced with `py-rust-stemmers` in 0.4.1, which ships wheels, so there is no compile step at install time anymore.

Closing this as completed.
